site_name: Keras-contrib Documentation
theme:
  name: null
  custom_dir: theme
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: false
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true

docs_dir: sources
repo_url: http://github.com/keras-team/keras
site_url: http://keras.io/
site_description: 'Documentation for Keras, the Python Deep Learning library.'

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-61785484-1', 'keras.io']

nav:
- Home: index.md
- Layers:
  - Core Layers: layers/core.md
  - Convolutional Layers: layers/convolutional.md
  - Advanced Activations Layers: layers/advanced-activations.md
  - Normalization Layers: layers/normalization.md
- Losses: losses.md
- Optimizers: optimizers.md
- Callbacks: callbacks.md
- Backend: backend.md
- Initializers: initializers.md
- Constraints: constraints.md
- Contributing: contributing.md
